"""VL53L0X register address constants."""

SYS_RANGE_START = 0x00
SYSTEM_SEQUENCE_CONFIG = 0x01
SYSTEM_INTERRUPT_CONFIG_GPIO = 0x0A
SYSTEM_INTERRUPT_CLEAR = 0x0B

RESULT_INTERRUPT_STATUS = 0x13
RESULT_RANGE_STATUS = 0x14

FINAL_RANGE_CONFIG_MIN_COUNT_RATE_RTN_LIMIT = 0x44
DYNAMIC_SPAD_NUM_REQUESTED_REF_SPAD = 0x4E
DYNAMIC_SPAD_REF_EN_START_OFFSET = 0x4F

PRE_RANGE_CONFIG_VCSEL_PERIOD = 0x50
FINAL_RANGE_CONFIG_VCSEL_PERIOD = 0x70

MSRC_CONFIG_TIMEOUT_MACROP = 0x46
PRE_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x51
FINAL_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x71

MSRC_CONFIG_CONTROL = 0x60

GPIO_HV_MUX_ACTIVE_HIGH = 0x84

GLOBAL_CONFIG_SPAD_ENABLES_REF_0 = 0xB0
GLOBAL_CONFIG_REF_EN_START_SELECT = 0xB6
