"""
Type stubs for the _rev_rhsplib C extension module.

This file is auto-maintained alongside src/_rev_rhsplib.cpp.
"""

from enum import IntEnum

# ── Error ─────────────────────────────────────────────────────────────────────

class RhspLibError(RuntimeError):
    """Exception raised when librhsp returns an error code.

    Attributes:
        error_code: The negative librhsp error code (e.g. ``ERROR_TIMEOUT``).
        nack_code: NACK reason code from the hub (only present when
            ``error_code == ERROR_NACK_RECEIVED``).
    """

    error_code: int
    nack_code: int  # only present when error_code == ERROR_NACK_RECEIVED

# ── Enums ─────────────────────────────────────────────────────────────────────

class SerialParity(IntEnum):
    None_: int
    Odd: int
    Even: int

class SerialFlowControl(IntEnum):
    None_: int
    Hardware: int
    Software: int

# ── Error code constants ──────────────────────────────────────────────────────

RESULT_OK: int
ERROR_GENERAL: int
ERROR_TIMEOUT: int
ERROR_MSG_NUMBER_MISMATCH: int
ERROR_NACK_RECEIVED: int
ERROR_SERIAL: int
ERROR_NOT_OPENED: int
ERROR_COMMAND_NOT_SUPPORTED: int
ERROR_UNEXPECTED_RESPONSE: int
ERROR_NO_HUBS_DISCOVERED: int
ERROR_ARG0_OUT_OF_RANGE: int
ERROR_ARG5_OUT_OF_RANGE: int
SERIAL_ERROR_GENERAL: int
SERIAL_ERROR_OPENING: int
SERIAL_ERROR_ARGS: int
SERIAL_ERROR_CONFIGURE: int
SERIAL_ERROR_IO: int

# ── Serial ────────────────────────────────────────────────────────────────────

class Serial:
    """Synchronous serial port wrapper.  Use :class:`rev_rhsplib.Serial` for async."""

    def __init__(self) -> None: ...
    def open(
        self,
        port: str,
        baudrate: int,
        databits: int,
        parity: SerialParity,
        stopbits: int,
        flow_control: SerialFlowControl,
    ) -> None: ...
    def close(self) -> None: ...
    def read(self, num_bytes: int) -> list[int]: ...
    def write(self, bytes: list[int]) -> None: ...

# ── RevHub ────────────────────────────────────────────────────────────────────

class RevHub:
    """Synchronous REV Hub wrapper.  Use :class:`rev_rhsplib.RevHub` for async."""

    def __init__(self) -> None: ...
    def open(self, serial: Serial, dest_address: int) -> None: ...
    def is_opened(self) -> bool: ...
    def close(self) -> None: ...
    def set_dest_address(self, addr: int) -> None: ...
    def get_dest_address(self) -> int: ...
    def set_response_timeout_ms(self, ms: int) -> None: ...
    def get_response_timeout_ms(self) -> int: ...

    # Custom commands
    def send_write_command(self, packet_type_id: int, payload: list[int]) -> list[int]: ...
    def send_read_command(self, packet_type_id: int, payload: list[int]) -> list[int]: ...

    # Module status / control
    def get_module_status(self, clear: bool) -> dict[str, int]: ...
    def send_keep_alive(self) -> None: ...
    def send_fail_safe(self) -> None: ...
    def set_new_module_address(self, new_addr: int) -> None: ...
    def query_interface(self, name: str) -> dict[str, object]: ...
    def get_interface_packet_id(self, name: str, function_number: int) -> int: ...
    def set_debug_log_level(self, group: int, level: int) -> None: ...

    # LED
    def set_module_led_color(self, red: int, green: int, blue: int) -> None: ...
    def get_module_led_color(self) -> tuple[int, int, int]: ...
    def set_module_led_pattern(self, steps: list[int]) -> None: ...
    def get_module_led_pattern(self) -> list[int]: ...

    # Device control
    def get_bulk_input_data(self) -> dict[str, int]: ...
    def get_adc(self, channel: int, raw_mode: int) -> int: ...
    def phone_charge_control(self, enable: bool) -> None: ...
    def phone_charge_query(self) -> bool: ...
    def inject_data_log_hint(self, hint: str) -> None: ...
    def read_version_string(self) -> str: ...
    def read_version(self) -> dict[str, int]: ...
    def ftdi_reset_control(self, enable: bool) -> None: ...
    def ftdi_reset_query(self) -> bool: ...

    # Digital I/O
    def set_single_digital_output(self, pin: int, value: bool) -> None: ...
    def set_all_digital_outputs(self, packed: int) -> None: ...
    def set_digital_direction(self, pin: int, direction_output: int) -> None: ...
    def get_digital_direction(self, pin: int) -> int: ...
    def get_single_digital_input(self, pin: int) -> bool: ...
    def get_all_digital_inputs(self) -> int: ...

    # I2C
    def configure_i2c_channel(self, channel: int, speed_code: int) -> None: ...
    def configure_i2c_query(self, channel: int) -> int: ...
    def write_single_byte(self, channel: int, addr: int, byte: int) -> None: ...
    def write_multiple_bytes(self, channel: int, addr: int, bytes: list[int]) -> None: ...
    def write_status_query(self, channel: int) -> dict[str, int]: ...
    def read_single_byte(self, channel: int, addr: int) -> None: ...
    def read_multiple_bytes(self, channel: int, addr: int, n: int) -> None: ...
    def write_read_multiple_bytes(
        self, channel: int, addr: int, n: int, start_address: int
    ) -> None: ...
    def read_status_query(self, channel: int) -> dict[str, object]: ...

    # Motor
    def set_motor_channel_mode(self, channel: int, mode: int, float_at_zero: bool) -> None: ...
    def get_motor_channel_mode(self, channel: int) -> dict[str, object]: ...
    def set_motor_channel_enable(self, channel: int, enable: bool) -> None: ...
    def get_motor_channel_enable(self, channel: int) -> bool: ...
    def set_motor_channel_current_alert_level(self, channel: int, limit_ma: int) -> None: ...
    def get_motor_channel_current_alert_level(self, channel: int) -> int: ...
    def reset_encoder(self, channel: int) -> None: ...
    def set_motor_constant_power(self, channel: int, power: float) -> None: ...
    def get_motor_constant_power(self, channel: int) -> float: ...
    def set_motor_target_velocity(self, channel: int, velocity_cps: int) -> None: ...
    def get_motor_target_velocity(self, channel: int) -> int: ...
    def set_motor_target_position(self, channel: int, position: int, tolerance: int) -> None: ...
    def get_motor_target_position(self, channel: int) -> dict[str, int]: ...
    def is_motor_at_target(self, channel: int) -> bool: ...
    def get_encoder_position(self, channel: int) -> int: ...
    def set_closed_loop_control_coefficients(
        self, channel: int, mode: int, params: dict[str, object]
    ) -> None: ...
    def get_closed_loop_control_coefficients(
        self, channel: int, mode: int
    ) -> dict[str, object]: ...

    # Servo
    def set_servo_configuration(self, channel: int, frame_period: int) -> None: ...
    def get_servo_configuration(self, channel: int) -> int: ...
    def set_servo_pulse_width(self, channel: int, width: int) -> None: ...
    def get_servo_pulse_width(self, channel: int) -> int: ...
    def set_servo_enable(self, channel: int, enable: bool) -> None: ...
    def get_servo_enable(self, channel: int) -> bool: ...

    # Static
    @staticmethod
    def discover_rev_hubs(serial: Serial) -> dict[str, object]: ...
